apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mysql-tcp
  namespace: iotdb-dev
spec:
  entryPoints:
    - mysql
  routes:
    - match: HostSNI(`*`)
      services:
        - name: mysql
          port: 3306
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: iotdb-tcp
  namespace: iotdb-dev
spec:
  entryPoints:
    - iotdb
  routes:
    - match: HostSNI(`*`)
      services:
        - name: iotdb
          port: 6667
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: flink-tcp
  namespace: iotdb-dev
spec:
  entryPoints:
    - flink
  routes:
    - match: HostSNI(`*`)
      services:
        - name: flink-jobmanager
          port: 8081