namespace: dev
resources:
  - ../../base
  - ingressroute-tcp.yaml
patches:
  - path: flink-config-patch.yaml
    target:
      kind: ConfigMap
      name: flink-config
  # - path: flink-resources.yaml
  - path: aliyun-image-mirror.yaml
  - path: iotdb-storageclass-patch.yaml
  - path: flink-tz-env-patch.yaml
