apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: iotdb-tcp
spec:
  entryPoints:
    - iotdb
  routes:
    - match: HostSNI(`*`)
      services:
        - name: iotdb
          port: 6667

