namespace: staging
resources:
  - ../../base
  - ingressroute-tcp.yaml
patches:
  - path: flink-config-patch.yaml
    target:
      kind: ConfigMap
      name: flink-config
  - path: flink-resources.yaml
